services:
  app:
    build: .
    image: stefanos26/disaster-relief:1.0.0
    container_name: my_node_app
    restart: always
    depends_on:
      - database
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      DATABASE_URL: 'postgresql://my_new_user:mysecret@database:5432/my_new_db'
    entrypoint: ['/bin/sh', '-c']
    command:
      - |
        npx prisma migrate deploy
        npx ts-node-dev --respawn --transpile-only src/devServer.ts

  database:
    image: postgres:17
    container_name: my_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: my_new_user
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: my_new_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  prisma-studio:
    image: node:18-alpine
    container_name: prisma_studio
    working_dir: /app
    command: sh -c "npx prisma studio --port 5555 --browser none"
    volumes:
      - .:/app
    ports:
      - '5555:5555'
    environment:
      DATABASE_URL: 'postgresql://my_new_user:mysecret@database:5432/my_new_db'
    depends_on:
      - database

volumes:
  pgdata:
